export default {
    "ad": "Andorra",
    "ae": "Emiratos Árabes Unidos",
    "af": "Afganistán",
    "ag": "Antigua y Barbuda",
    "ai": "Anguila",
    "al": "Albania",
    "am": "Armenia",
    "ao": "Angola",
    "ar": "Argentina",
    "as": "Samoa Americana",
    "at": "Austria",
    "au": "Australia",
    "aw": "Aruba",
    "az": "Azerbaiyán",
    "ba": "Bosnia-Herzegovina",
    "bb": "Barbados",
    "bd": "Bangladés",
    "be": "Bélgica",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "bh": "Baréin",
    "bi": "Burundi",
    "bj": "Benín",
    "bm": "Bermudas",
    "bn": "Brunéi",
    "bo": "Bolivia",
    "br": "Brasil",
    "bs": "Bahamas",
    "bt": "Bután",
    "bw": "Botsuana",
    "by": "Bielorrusia",
    "bz": "Belice",
    "ca": "Canadá",
    "cd": "Congo (RD)",
    "cf": "República Centroafricana",
    "cg": "Congo",
    "ch": "Suiza",
    "ci": "Costa de Marfil",
    "ck": "Islas Cook",
    "cl": "Chile",
    "cm": "Camerún",
    "cn": "China (República Popular)",
    "co": "Colombia",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cv": "Cabo Verde",
    "cw": "Curazao",
    "cy": "Chipre",
    "cz": "República Checa",
    "de": "Alemania",
    "dj": "Yibuti",
    "dk": "Dinamarca",
    "dm": "Dominica",
    "do": "República Dominicana",
    "dz": "Argelia",
    "ec": "Ecuador",
    "ee": "Estonia",
    "eg": "Egipto",
    "er": "Eritrea",
    "es": "España",
    "et": "Etiopía",
    "fi": "Finlandia",
    "fj": "Fiyi",
    "fm": "Micronesia",
    "fr": "Francia",
    "ga": "Gabón",
    "gb": "Reino Unido",
    "gd": "Granada",
    "ge": "Georgia",
    "gh": "Ghana",
    "gl": "Groenlandia",
    "gm": "Gambia",
    "gn": "Guinea",
    "gq": "Guinea Ecuatorial",
    "gr": "Grecia",
    "gt": "Guatemala",
    "gu": "Guam",
    "gw": "Guinea-Bisáu",
    "gy": "Guyana",
    "hk": "Hong Kong",
    "hn": "Honduras",
    "hr": "Croacia",
    "ht": "Haití",
    "hu": "Hungría",
    "id": "Indonesia",
    "ie": "Irlanda",
    "il": "Israel",
    "in": "India",
    "iq": "Irak",
    "ir": "Irán",
    "is": "Islandia",
    "it": "Italia",
    "jm": "Jamaica",
    "jo": "Jordania",
    "jp": "Japón",
    "ke": "Kenia",
    "kg": "Kirguizistán",
    "kh": "Camboya",
    "ki": "Kiribati",
    "km": "Comoras",
    "kn": "San Cristóbal y Nieves",
    "kp": "Corea del Norte",
    "kr": "Corea del Sur",
    "kw": "Kuwait",
    "ky": "Islas Caimán",
    "kz": "Kazajistán",
    "la": "Laos",
    "lb": "Líbano",
    "lc": "Santa Lucía",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lr": "Liberia",
    "ls": "Lesoto",
    "lt": "Lituania",
    "lu": "Luxemburgo",
    "lv": "Letonia",
    "ly": "Libia",
    "ma": "Marruecos",
    "mc": "Mónaco",
    "md": "Moldavia",
    "me": "Montenegro",
    "mg": "Madagascar",
    "mk": "Macedonia",
    "ml": "Malí",
    "mm": "Birmania (Myanmar)",
    "mn": "Mongolia",
    "mo": "Macao",
    "mr": "Mauritania",
    "mt": "Malta",
    "mu": "Mauricio",
    "mv": "Maldivas",
    "mw": "Malaui",
    "mx": "México",
    "my": "Malasia",
    "mz": "Mozambique",
    "na": "Namibia",
    "ne": "Níger",
    "ng": "Nigeria",
    "ni": "Nicaragua",
    "nl": "Países Bajos",
    "no": "Noruega",
    "np": "Nepal",
    "nr": "Nauru",
    "nz": "Nueva Zelanda",
    "om": "Omán",
    "pa": "Panamá",
    "pe": "Perú",
    "pg": "Papúa Nueva Guinea",
    "ph": "Filipinas",
    "pk": "Pakistán",
    "pl": "Polonia",
    "pr": "Puerto Rico",
    "pt": "Portugal",
    "pw": "Palaos",
    "py": "Paraguay",
    "qa": "Catar",
    "ro": "Rumania",
    "rs": "Serbia",
    "ru": "Rusia",
    "rw": "Ruanda",
    "sa": "Arabia Saudita",
    "sb": "Islas Salomón",
    "sc": "Seychelles",
    "sd": "Sudán",
    "se": "Suecia",
    "sg": "Singapur",
    "si": "Eslovenia",
    "sk": "Eslovaquia",
    "sl": "Sierra Leona",
    "sm": "San Marino",
    "sn": "Senegal",
    "so": "Somalia",
    "sr": "Surinam",
    "ss": "Sudán del Sur",
    "st": "Santo Tomé y Príncipe",
    "sv": "El Salvador",
    "sy": "Siria",
    "sz": "Suazilandia",
    "td": "Chad",
    "tg": "Togo",
    "th": "Tailandia",
    "tj": "Tayikistán",
    "tk": "Tokelau",
    "tl": "Timor Oriental",
    "tm": "Turkmenistán",
    "tn": "Túnez",
    "to": "Tonga",
    "tr": "Turquía",
    "tt": "Trinidad y Tobago",
    "tv": "Tuvalu",
    "tw": "Taiwán (República de China)",
    "tz": "Tanzania",
    "ua": "Ucrania",
    "ug": "Uganda",
    "us": "Estados Unidos",
    "uy": "Uruguay",
    "uz": "Uzbekistán",
    "va": "Ciudad del Vaticano",
    "vc": "San Vicente y las Granadinas",
    "ve": "Venezuela",
    "vn": "Vietnam",
    "vu": "Vanuatu",
    "ws": "Samoa",
    "ye": "Yemen",
    "za": "Sudáfrica",
    "zm": "Zambia",
    "zw": "Zimbabue"
};
