export default {
    "AD": "Andorra",
    "AE": "Emiratos Árabes Unidos",
    "AF": "Afganistán",
    "AG": "Antigua y Barbuda",
    "AI": "Anguila",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AR": "Argentina",
    "AS": "Samoa Americana",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AZ": "Azerbaiyán",
    "BA": "Bosnia-Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladés",
    "BE": "Bélgica",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Baréin",
    "BI": "Burundi",
    "BJ": "Benín",
    "BM": "Bermudas",
    "BN": "Brunéi",
    "BO": "Bolivia",
    "BR": "Brasil",
    "BS": "Bahamas",
    "BT": "Bután",
    "BW": "Botsuana",
    "BY": "Bielorrusia",
    "BZ": "Belice",
    "CA": "Canadá",
    "CD": "Congo (RD)",
    "CF": "República Centroafricana",
    "CG": "Congo",
    "CH": "Suiza",
    "CI": "Costa de Marfil",
    "CK": "Islas Cook",
    "CL": "Chile",
    "CM": "Camerún",
    "CN": "China (República Popular)",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curazao",
    "CY": "Chipre",
    "CZ": "República Checa",
    "DE": "Alemania",
    "DJ": "Yibuti",
    "DK": "Dinamarca",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "DZ": "Argelia",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egipto",
    "ER": "Eritrea",
    "ES": "España",
    "ET": "Etiopía",
    "FI": "Finlandia",
    "FJ": "Fiyi",
    "FM": "Micronesia",
    "FR": "Francia",
    "GA": "Gabón",
    "GB": "Reino Unido",
    "GD": "Granada",
    "GE": "Georgia",
    "GH": "Ghana",
    "GL": "Groenlandia",
    "GM": "Gambia",
    "GN": "Guinea",
    "GQ": "Guinea Ecuatorial",
    "GR": "Grecia",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bisáu",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HN": "Honduras",
    "HR": "Croacia",
    "HT": "Haití",
    "HU": "Hungría",
    "ID": "Indonesia",
    "IE": "Irlanda",
    "IL": "Israel",
    "IN": "India",
    "IQ": "Irak",
    "IR": "Irán",
    "IS": "Islandia",
    "IT": "Italia",
    "JM": "Jamaica",
    "JO": "Jordania",
    "JP": "Japón",
    "KE": "Kenia",
    "KG": "Kirguizistán",
    "KH": "Camboya",
    "KI": "Kiribati",
    "KM": "Comoras",
    "KN": "San Cristóbal y Nieves",
    "KP": "Corea del Norte",
    "KR": "Corea del Sur",
    "KW": "Kuwait",
    "KY": "Islas Caimán",
    "KZ": "Kazajistán",
    "LA": "Laos",
    "LB": "Líbano",
    "LC": "Santa Lucía",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesoto",
    "LT": "Lituania",
    "LU": "Luxemburgo",
    "LV": "Letonia",
    "LY": "Libia",
    "MA": "Marruecos",
    "MC": "Mónaco",
    "MD": "Moldavia",
    "ME": "Montenegro",
    "MG": "Madagascar",
    "MK": "Macedonia",
    "ML": "Malí",
    "MM": "Birmania (Myanmar)",
    "MN": "Mongolia",
    "MO": "Macao",
    "MR": "Mauritania",
    "MT": "Malta",
    "MU": "Mauricio",
    "MV": "Maldivas",
    "MW": "Malaui",
    "MX": "México",
    "MY": "Malasia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NE": "Níger",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Países Bajos",
    "NO": "Noruega",
    "NP": "Nepal",
    "NR": "Nauru",
    "NZ": "Nueva Zelanda",
    "OM": "Omán",
    "PA": "Panamá",
    "PE": "Perú",
    "PG": "Papúa Nueva Guinea",
    "PH": "Filipinas",
    "PK": "Pakistán",
    "PL": "Polonia",
    "PR": "Puerto Rico",
    "PT": "Portugal",
    "PW": "Palaos",
    "PY": "Paraguay",
    "QA": "Catar",
    "RO": "Rumania",
    "RS": "Serbia",
    "RU": "Rusia",
    "RW": "Ruanda",
    "SA": "Arabia Saudita",
    "SB": "Islas Salomón",
    "SC": "Seychelles",
    "SD": "Sudán",
    "SE": "Suecia",
    "SG": "Singapur",
    "SI": "Eslovenia",
    "SK": "Eslovaquia",
    "SL": "Sierra Leona",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Surinam",
    "SS": "Sudán del Sur",
    "ST": "Santo Tomé y Príncipe",
    "SV": "El Salvador",
    "SY": "Siria",
    "SZ": "Suazilandia",
    "TD": "Chad",
    "TG": "Togo",
    "TH": "Tailandia",
    "TJ": "Tayikistán",
    "TK": "Tokelau",
    "TL": "Timor Oriental",
    "TM": "Turkmenistán",
    "TN": "Túnez",
    "TO": "Tonga",
    "TR": "Turquía",
    "TT": "Trinidad y Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwán (República de China)",
    "TZ": "Tanzania",
    "UA": "Ucrania",
    "UG": "Uganda",
    "US": "Estados Unidos",
    "UY": "Uruguay",
    "UZ": "Uzbekistán",
    "VA": "Ciudad del Vaticano",
    "VC": "San Vicente y las Granadinas",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WS": "Samoa",
    "YE": "Yemen",
    "ZA": "Sudáfrica",
    "ZM": "Zambia",
    "ZW": "Zimbabue"
};
