export default {
    "ad": "Andorre",
    "ae": "Émirats arabes unis",
    "af": "Afghanistan",
    "ag": "Antigua-et-Barbuda",
    "ai": "Anguilla",
    "al": "Albanie",
    "am": "Arménie",
    "ao": "Angola",
    "ar": "Argentine",
    "as": "Samoa américain",
    "at": "Autriche",
    "au": "Australie",
    "aw": "Aruba",
    "az": "Azerbaïdjan",
    "ba": "Bosnie-Herzégovine",
    "bb": "Barbade",
    "bd": "Bangladesh",
    "be": "Belgique",
    "bf": "Burkina Faso",
    "bg": "Bulgarie",
    "bh": "Bahreïn",
    "bi": "Burundi",
    "bj": "Bénin",
    "bm": "Bermudes",
    "bn": "Brunei",
    "bo": "Bolivie",
    "br": "Brésil",
    "bs": "Bahamas",
    "bt": "Bhoutan",
    "bw": "Botswana",
    "by": "Bélarus",
    "bz": "Belize",
    "ca": "Canada",
    "cd": "Congo (DR)",
    "cf": "République centrafricaine",
    "cg": "Congo",
    "ch": "Suisse",
    "ci": "Côte D'Ivoire",
    "ck": "Îles Cook",
    "cl": "Chili",
    "cm": "Cameroun",
    "cn": "Chine (République populaire)",
    "co": "Colombie",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cv": "Cap-Vert",
    "cw": "Curaçao",
    "cy": "Chypre",
    "cz": "République tchèque",
    "de": "Allemagne",
    "dj": "Djibouti",
    "dk": "Danemark",
    "dm": "Dominique",
    "do": "République dominicaine",
    "dz": "Algérie",
    "ec": "Équateur",
    "ee": "Estonie",
    "eg": "Egypte",
    "er": "Erythrée",
    "es": "Espagne",
    "et": "Ethiopie",
    "fi": "Finlande",
    "fj": "Fidji",
    "fm": "Micronésie",
    "fr": "France",
    "ga": "Gabon",
    "gb": "Royaume-Uni",
    "gd": "Grenade",
    "ge": "Géorgie",
    "gh": "Ghana",
    "gl": "Groenland",
    "gm": "Gambie",
    "gn": "Guinée",
    "gq": "Guinée équatoriale",
    "gr": "Grèce",
    "gt": "Guatemala",
    "gu": "Guam",
    "gw": "Guinée-Bissau",
    "gy": "Guyane",
    "hk": "Hong-Kong",
    "hn": "Honduras",
    "hr": "Croatie",
    "ht": "Haïti",
    "hu": "Hongrie",
    "id": "Indonésie",
    "ie": "Irlande",
    "il": "Israël",
    "in": "Inde",
    "iq": "Irak",
    "ir": "Iran",
    "is": "Islande",
    "it": "Italie",
    "jm": "Jamaïque",
    "jo": "Jordanie",
    "jp": "Japon",
    "ke": "Kenya",
    "kg": "Kirghizistan",
    "kh": "Cambodge",
    "ki": "Kiribati",
    "km": "Comores",
    "kn": "Saint-Christophe-et-Niévès",
    "kp": "Corée du Nord",
    "kr": "Corée du Sud",
    "kw": "Koweit",
    "ky": "Îles Caïmans",
    "kz": "Kazakhstan",
    "la": "Laos",
    "lb": "Liban",
    "lc": "Sainte-Lucie",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lr": "Libéria",
    "ls": "Lesotho",
    "lt": "Lituanie",
    "lu": "Luxembourg",
    "lv": "Lettonie",
    "ly": "Libye",
    "ma": "Maroc",
    "mc": "Monaco",
    "md": "Moldavie",
    "me": "Monténégro",
    "mg": "Madagascar",
    "mk": "Macédoine",
    "ml": "Mali",
    "mm": "Myanmar",
    "mn": "Mongolie",
    "mo": "Macao",
    "mr": "Mauritanie",
    "mt": "Malte",
    "mu": "Maurice",
    "mv": "Maldives",
    "mw": "Malawi",
    "mx": "Mexique",
    "my": "Malaisie",
    "mz": "Mozambique",
    "na": "Namibie",
    "ne": "Niger",
    "ng": "Nigeria",
    "ni": "Nicaragua",
    "nl": "Pays-Bas",
    "no": "Norvège",
    "np": "Népal",
    "nr": "Nauru",
    "nz": "Nouvelle-Zélande",
    "om": "Oman",
    "pa": "Panama",
    "pe": "Pérou",
    "pg": "Papouasie-Nouvelle-Guinée",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Pologne",
    "pr": "Puerto Rico",
    "pt": "Portugal",
    "pw": "Palau",
    "py": "Paraguay",
    "qa": "Qatar",
    "ro": "Roumanie",
    "rs": "Serbie",
    "ru": "Russie",
    "rw": "Rwanda",
    "sa": "Arabie Saoudite",
    "sb": "Îles Salomon",
    "sc": "Seychelles",
    "sd": "Soudan",
    "se": "Suède",
    "sg": "Singapour",
    "si": "Slovénie",
    "sk": "Slovaquie",
    "sl": "Sierra Leone",
    "sm": "San Marino",
    "sn": "Sénégal",
    "so": "Somalie",
    "sr": "Suriname",
    "ss": "Sud-Soudan",
    "st": "Sao Tomé et Principe",
    "sv": "El Salvador",
    "sy": "Syrie",
    "sz": "Swaziland",
    "td": "Tchad",
    "tg": "Togo",
    "th": "Thaïlande",
    "tj": "Tadjikistan",
    "tk": "Tokelau",
    "tl": "Timor-Leste",
    "tm": "Turkménistan",
    "tn": "Tunisie",
    "to": "Tonga",
    "tr": "Turquie",
    "tt": "Trinité-et-Tobago",
    "tv": "Tuvalu",
    "tw": "Taïwan (République de Chine)",
    "tz": "Tanzanie",
    "ua": "Ukraine",
    "ug": "Ouganda",
    "us": "États-Unis",
    "uy": "Uruguay",
    "uz": "Ouzbékistan",
    "va": "Cité du Vatican",
    "vc": "Saint-Vincent-et-les-Grenadines",
    "ve": "Venezuela",
    "vn": "Viêt-Nam",
    "vu": "Vanuatu",
    "ws": "Samoa",
    "ye": "Yémen",
    "za": "Afrique du Sud",
    "zm": "Zambie",
    "zw": "Zimbabwe"
};
