export default {
    "ad": "Andorra",
    "ae": "Emirati Arabi Uniti",
    "af": "Afghanistan",
    "ag": "Antigua e Barbuda",
    "ai": "Anguilla",
    "al": "Albania",
    "am": "Armenia",
    "ao": "Angola",
    "ar": "Argentina",
    "as": "Samoa Americane",
    "at": "Austria",
    "au": "Australia",
    "aw": "Aruba",
    "az": "Azerbaigian",
    "ba": "Bosnia ed Erzegovina",
    "bb": "Barbados",
    "bd": "Bangladesh",
    "be": "Belgio",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "bh": "Bahrain",
    "bi": "Burundi",
    "bj": "Benin",
    "bm": "Bermuda",
    "bn": "Brunei",
    "bo": "Bolivia",
    "br": "Brasile",
    "bs": "Bahamas",
    "bt": "Bhutan",
    "bw": "Botswana",
    "by": "Bielorussia",
    "bz": "Belize",
    "ca": "Canada",
    "cd": "Congo (RD)",
    "cf": "Repubblica Centrafricana",
    "cg": "Congo",
    "ch": "Svizzera",
    "ci": "Costa d'Avorio",
    "ck": "Isole Cook",
    "cl": "Cile",
    "cm": "Camerun",
    "cn": "Cina (Repubblica Popolare)",
    "co": "Colombia",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cv": "Capo Verde",
    "cw": "Curaçao",
    "cy": "Cipro",
    "cz": "Repubblica Ceca",
    "de": "Germania",
    "dj": "Gibuti",
    "dk": "Danimarca",
    "dm": "Dominica",
    "do": "Repubblica Dominicana",
    "dz": "Algeria",
    "ec": "Ecuador",
    "ee": "Estonia",
    "eg": "Egitto",
    "er": "Eritrea",
    "es": "Spagna",
    "et": "Etiopia",
    "fi": "Finlandia",
    "fj": "Figi",
    "fm": "Micronesia",
    "fr": "Francia",
    "ga": "Gabon",
    "gb": "Regno Unito",
    "gd": "Grenada",
    "ge": "Georgia",
    "gh": "Ghana",
    "gl": "Groenlandia",
    "gm": "Gambia",
    "gn": "Guinea",
    "gq": "Guinea Equatoriale",
    "gr": "Grecia",
    "gt": "Guatemala",
    "gu": "Guam",
    "gw": "Guinea-Bissau",
    "gy": "Guyana",
    "hk": "Hong Kong",
    "hn": "Honduras",
    "hr": "Croazia",
    "ht": "Haiti",
    "hu": "Ungheria",
    "id": "Indonesia",
    "ie": "Irlanda",
    "il": "Israele",
    "in": "India",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Islanda",
    "it": "Italia",
    "jm": "Giamaica",
    "jo": "Giordania",
    "jp": "Giappone",
    "ke": "Kenya",
    "kg": "Kirghizistan",
    "kh": "Cambogia",
    "ki": "Kiribati",
    "km": "Comore",
    "kn": "Saint Kitts e Nevis",
    "kp": "Corea del Nord",
    "kr": "Corea del Sud",
    "kw": "Kuwait",
    "ky": "Isole Cayman",
    "kz": "Kazakistan",
    "la": "Laos",
    "lb": "Libano",
    "lc": "Santa Lucia",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lr": "Liberia",
    "ls": "Lesotho",
    "lt": "Lituania",
    "lu": "Lussemburgo",
    "lv": "Lettonia",
    "ly": "Libia",
    "ma": "Marocco",
    "mc": "Monaco",
    "md": "Moldavia",
    "me": "Montenegro",
    "mg": "Madagascar",
    "mk": "Macedonia",
    "ml": "Mali",
    "mm": "Birmania",
    "mn": "Mongolia",
    "mo": "Macao",
    "mr": "Mauritania",
    "mt": "Malta",
    "mu": "Mauritius",
    "mv": "Maldive",
    "mw": "Malawi",
    "mx": "Messico",
    "my": "Malesia",
    "mz": "Mozambico",
    "na": "Namibia",
    "ne": "Niger",
    "ng": "Nigeria",
    "ni": "Nicaragua",
    "nl": "Olanda",
    "no": "Norvegia",
    "np": "Nepal",
    "nr": "Nauru",
    "nz": "Nuova Zelanda",
    "om": "Oman",
    "pa": "Panamá",
    "pe": "Perù",
    "pg": "Papua Nuova Guinea",
    "ph": "Filippine",
    "pk": "Pakistan",
    "pl": "Polonia",
    "pr": "Porto Rico",
    "pt": "Portogallo",
    "pw": "Palau",
    "py": "Paraguay",
    "qa": "Qatar",
    "ro": "Romania",
    "ru": "Russia",
    "rs": "Serbia",
    "rw": "Ruanda",
    "sa": "Arabia Saudita",
    "sb": "Isole Salomone",
    "sc": "Seychelles",
    "sd": "Sudan",
    "se": "Svezia",
    "sg": "Singapore",
    "si": "Slovenia",
    "sk": "Slovacchia",
    "sl": "Sierra Leone",
    "sm": "San Marino",
    "sn": "Senegal",
    "so": "Somalia",
    "sr": "Suriname",
    "ss": "Sudan del Sud",
    "st": "São Tomé e Príncipe",
    "sv": "El Salvador",
    "sy": "Siria",
    "sz": "Swaziland",
    "td": "Ciad",
    "tg": "Togo",
    "th": "Thailandia",
    "tj": "Tagikistan",
    "tk": "Tokelau",
    "tl": "Timor Est",
    "tm": "Turkmenistan",
    "tn": "Tunisia",
    "to": "Tonga",
    "tr": "Turchia",
    "tt": "Trinidad e Tobago",
    "tv": "Tuvalu",
    "tw": "Taiwan (Repubblica di Cina)",
    "tz": "Tanzania",
    "ua": "Ucraina",
    "ug": "Uganda",
    "us": "Stati Uniti d'America",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "va": "Città del Vaticano",
    "vc": "Saint Vincent e Grenadine",
    "ve": "Venezuela",
    "vn": "Vietnam",
    "vu": "Vanuatu",
    "ws": "Samoa",
    "ye": "Yemen",
    "za": "Sudafrica",
    "zm": "Zambia",
    "zw": "Zimbabwe"
};
