export default {
    "ad": "Andorra",
    "ae": "Emirados Árabes Unidos",
    "af": "Afeganistão",
    "ag": "Antígua e Barbuda",
    "ai": "Anguilla",
    "al": "Albânia",
    "am": "Armênia",
    "ao": "Angola",
    "ar": "Argentina",
    "as": "Samoa americana",
    "at": "Áustria",
    "au": "Austrália",
    "aw": "Aruba",
    "az": "Azerbaijão",
    "ba": "Bósnia e Herzegovina",
    "bb": "Barbados",
    "bd": "Bangladesh",
    "be": "Bélgica",
    "bf": "Burkina Faso",
    "bg": "Bulgária",
    "bh": "Bahrain",
    "bi": "Burundi",
    "bj": "Benin",
    "bm": "Bermudas",
    "bn": "Brunei",
    "bo": "Bolívia",
    "br": "Brasil",
    "bs": "Bahamas",
    "bt": "Butão",
    "bw": "Botswana",
    "by": "Belarus",
    "bz": "Belize",
    "ca": "Canadá",
    "cd": "Congo (RD)",
    "cf": "República Centro-Africana",
    "cg": "Congo",
    "ch": "Suíça",
    "ci": "Costa do Marfim",
    "ck": "Ilhas Cook",
    "cl": "Chile",
    "cm": "Camarões",
    "cn": "China (República Popular)",
    "co": "Colômbia",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cv": "Cabo Verde",
    "cw": "Curacao",
    "cy": "Chipre",
    "cz": "República Checa",
    "de": "Alemanha",
    "dj": "Djibouti",
    "dk": "Dinamarca",
    "dm": "Dominica",
    "do": "República Dominicana",
    "dz": "Argélia",
    "ec": "Equador",
    "ee": "Estônia",
    "eg": "Egito",
    "er": "Eritreia",
    "es": "Espanha",
    "et": "Etiópia",
    "fi": "Finlândia",
    "fj": "Fiji",
    "fm": "Micronésia",
    "fr": "França",
    "ga": "Gabão",
    "gb": "Reino Unido",
    "gd": "Granada",
    "ge": "Georgia",
    "gh": "Gana",
    "gl": "Groenlândia",
    "gm": "Gâmbia",
    "gn": "Guiné",
    "gq": "Guiné Equatorial",
    "gr": "Grécia",
    "gt": "Guatemala",
    "gu": "Guam",
    "gw": "Guiné-Bissau",
    "gy": "Guiana",
    "hk": "Hong Kong",
    "hn": "Honduras",
    "hr": "Croácia",
    "ht": "Haiti",
    "hu": "Hungria",
    "id": "Indonésia",
    "ie": "Irlanda",
    "il": "Israel",
    "in": "Índia",
    "iq": "Iraque",
    "ir": "Irã",
    "is": "Islândia",
    "it": "Itália",
    "jm": "Jamaica",
    "jo": "Jordânia",
    "jp": "Japão",
    "ke": "Quênia",
    "kg": "Quirguistão",
    "kh": "Camboja",
    "ki": "Kiribati",
    "km": "Comores",
    "kn": "São Cristóvão e Nevis",
    "kp": "Coréia do Norte",
    "kr": "Coréia do Sul",
    "kw": "Kuweit",
    "ky": "Ilhas Cayman",
    "kz": "Cazaquistão",
    "la": "Laos",
    "lb": "Líbano",
    "lc": "St Lucia",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lr": "Libéria",
    "ls": "Lesoto",
    "lt": "Lituânia",
    "lu": "Luxemburgo",
    "lv": "Látvia",
    "ly": "Líbia",
    "ma": "Marrocos",
    "mc": "Mônaco",
    "md": "Moldávia",
    "me": "Montenegro",
    "mg": "Madagáscar",
    "mk": "Macedonia",
    "ml": "Mali",
    "mm": "Mianmar",
    "mn": "Mongólia",
    "mo": "Macau",
    "mr": "Mauritânia",
    "mt": "Malta",
    "mu": "Maurício",
    "mv": "Maldivas",
    "mw": "Malavi",
    "mx": "México",
    "my": "Malásia",
    "mz": "Moçambique",
    "na": "Namíbia",
    "ne": "Níger",
    "ng": "Nigéria",
    "ni": "Nicarágua",
    "nl": "Holanda",
    "no": "Noruega",
    "np": "Nepal",
    "nr": "Nauru",
    "nz": "Nova Zelândia",
    "om": "Oman",
    "pa": "Panamá",
    "pe": "Peru",
    "pg": "Papua Nova Guiné",
    "ph": "Filipinas",
    "pk": "Paquistão",
    "pl": "Polônia",
    "pr": "Porto Rico",
    "pt": "Portugal",
    "pw": "Palau",
    "py": "Paraguai",
    "qa": "Catar",
    "ro": "Romênia",
    "rs": "Sérvia",
    "ru": "Rússia",
    "rw": "Ruanda",
    "sa": "Arábia Saudita",
    "sb": "Ilhas Salomão",
    "sc": "Seychelles",
    "sd": "Sudão",
    "se": "Suécia",
    "sg": "Cingapura",
    "si": "Eslovenia",
    "sk": "Eslováquia",
    "sl": "Serra Leoa",
    "sm": "San Marino",
    "sn": "Senegal",
    "so": "Somália",
    "sr": "Suriname",
    "ss": "Sudão do Sul",
    "st": "São Tomé e Príncipe",
    "sv": "El Salvador",
    "sy": "Síria",
    "sz": "Suazilândia",
    "td": "Chade",
    "tg": "Togo",
    "th": "Tailândia",
    "tj": "Tadjiquistão",
    "tk": "Tokelau",
    "tl": "Timor-Leste",
    "tm": "Turquemenistão",
    "tn": "Tunísia",
    "to": "Tonga",
    "tr": "Turquia",
    "tt": "Trinidad e Tobago",
    "tv": "Tuvalu",
    "tw": "Taiwan (República da China)",
    "tz": "Tanzânia",
    "ua": "Ucrânia",
    "ug": "Uganda",
    "us": "Estados Unidos",
    "uy": "Uruguai",
    "uz": "Uzbequistão",
    "va": "Cidade do Vaticano",
    "vc": "São Vicente e Granadinas",
    "ve": "Venezuela",
    "vn": "Vietnã",
    "vu": "Vanuatu",
    "ws": "Samoa",
    "ye": "Iémen",
    "za": "África do Sul",
    "zm": "Zâmbia",
    "zw": "Zimbábue"
};
