export default {
    "AD": "Andorra",
    "AE": "Emirados Árabes Unidos",
    "AF": "Afeganistão",
    "AG": "Antígua e Barbuda",
    "AI": "Anguilla",
    "AL": "Albânia",
    "AM": "Armênia",
    "AO": "Angola",
    "AR": "Argentina",
    "AS": "Samoa americana",
    "AT": "Áustria",
    "AU": "Austrália",
    "AW": "Aruba",
    "AZ": "Azerbaijão",
    "BA": "Bósnia e Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Bélgica",
    "BF": "Burkina Faso",
    "BG": "Bulgária",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BM": "Bermudas",
    "BN": "Brunei",
    "BO": "Bolívia",
    "BR": "Brasil",
    "BS": "Bahamas",
    "BT": "Butão",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canadá",
    "CD": "Congo (RD)",
    "CF": "República Centro-Africana",
    "CG": "Congo",
    "CH": "Suíça",
    "CI": "Costa do Marfim",
    "CK": "Ilhas Cook",
    "CL": "Chile",
    "CM": "Camarões",
    "CN": "China (República Popular)",
    "CO": "Colômbia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curacao",
    "CY": "Chipre",
    "CZ": "República Checa",
    "DE": "Alemanha",
    "DJ": "Djibouti",
    "DK": "Dinamarca",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "DZ": "Argélia",
    "EC": "Equador",
    "EE": "Estônia",
    "EG": "Egito",
    "ER": "Eritreia",
    "ES": "Espanha",
    "ET": "Etiópia",
    "FI": "Finlândia",
    "FJ": "Fiji",
    "FM": "Micronésia",
    "FR": "França",
    "GA": "Gabão",
    "GB": "Reino Unido",
    "GD": "Granada",
    "GE": "Georgia",
    "GH": "Gana",
    "GL": "Groenlândia",
    "GM": "Gâmbia",
    "GN": "Guiné",
    "GQ": "Guiné Equatorial",
    "GR": "Grécia",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guiné-Bissau",
    "GY": "Guiana",
    "HK": "Hong Kong",
    "HN": "Honduras",
    "HR": "Croácia",
    "HT": "Haiti",
    "HU": "Hungria",
    "ID": "Indonésia",
    "IE": "Irlanda",
    "IL": "Israel",
    "IN": "Índia",
    "IQ": "Iraque",
    "IR": "Irã",
    "IS": "Islândia",
    "IT": "Itália",
    "JM": "Jamaica",
    "JO": "Jordânia",
    "JP": "Japão",
    "KE": "Quênia",
    "KG": "Quirguistão",
    "KH": "Camboja",
    "KI": "Kiribati",
    "KM": "Comores",
    "KN": "São Cristóvão e Nevis",
    "KP": "Coréia do Norte",
    "KR": "Coréia do Sul",
    "KW": "Kuweit",
    "KY": "Ilhas Cayman",
    "KZ": "Cazaquistão",
    "LA": "Laos",
    "LB": "Líbano",
    "LC": "St Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Libéria",
    "LS": "Lesoto",
    "LT": "Lituânia",
    "LU": "Luxemburgo",
    "LV": "Látvia",
    "LY": "Líbia",
    "MA": "Marrocos",
    "MC": "Mônaco",
    "MD": "Moldávia",
    "ME": "Montenegro",
    "MG": "Madagáscar",
    "MK": "Macedonia",
    "ML": "Mali",
    "MM": "Mianmar",
    "MN": "Mongólia",
    "MO": "Macau",
    "MR": "Mauritânia",
    "MT": "Malta",
    "MU": "Maurício",
    "MV": "Maldivas",
    "MW": "Malavi",
    "MX": "México",
    "MY": "Malásia",
    "MZ": "Moçambique",
    "NA": "Namíbia",
    "NE": "Níger",
    "NG": "Nigéria",
    "NI": "Nicarágua",
    "NL": "Holanda",
    "NO": "Noruega",
    "NP": "Nepal",
    "NR": "Nauru",
    "NZ": "Nova Zelândia",
    "OM": "Oman",
    "PA": "Panamá",
    "PE": "Peru",
    "PG": "Papua Nova Guiné",
    "PH": "Filipinas",
    "PK": "Paquistão",
    "PL": "Polônia",
    "PR": "Porto Rico",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguai",
    "QA": "Catar",
    "RO": "Romênia",
    "RS": "Sérvia",
    "RU": "Rússia",
    "RW": "Ruanda",
    "SA": "Arábia Saudita",
    "SB": "Ilhas Salomão",
    "SC": "Seychelles",
    "SD": "Sudão",
    "SE": "Suécia",
    "SG": "Cingapura",
    "SI": "Eslovenia",
    "SK": "Eslováquia",
    "SL": "Serra Leoa",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somália",
    "SR": "Suriname",
    "SS": "Sudão do Sul",
    "ST": "São Tomé e Príncipe",
    "SV": "El Salvador",
    "SY": "Síria",
    "SZ": "Suazilândia",
    "TD": "Chade",
    "TG": "Togo",
    "TH": "Tailândia",
    "TJ": "Tadjiquistão",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turquemenistão",
    "TN": "Tunísia",
    "TO": "Tonga",
    "TR": "Turquia",
    "TT": "Trinidad e Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan (República da China)",
    "TZ": "Tanzânia",
    "UA": "Ucrânia",
    "UG": "Uganda",
    "US": "Estados Unidos",
    "UY": "Uruguai",
    "UZ": "Uzbequistão",
    "VA": "Cidade do Vaticano",
    "VC": "São Vicente e Granadinas",
    "VE": "Venezuela",
    "VN": "Vietnã",
    "VU": "Vanuatu",
    "WS": "Samoa",
    "YE": "Iémen",
    "ZA": "África do Sul",
    "ZM": "Zâmbia",
    "ZW": "Zimbábue"
};
